from automation.standards.benchmarking_code_generation import BenchmarkingCodeGenerationTask
from automation.standards.benchmarking_chat import BenchmarkingChatTask
from automation.standards.benchmarking_instruction import BenchmarkingInstructionTask
from automation.standards.benchmarking_docstring_generation import BenchmarkingDocstringGenerationTask
from automation.standards.benchmarking_summarization import BenchmarkingSummarizationTask
from automation.standards.openllm import OpenLLMTask
from automation.standards.quantization_w4a16 import QuantizationW4A16Task
from automation.standards.pipeline_w4a16 import QuantizationW4A16Pipeline