apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlr-tier2-<YOUR_NAME>
  namespace: machine-learning
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs-tier2
  resources:
    requests:
      storage: 1Ti
